server {
    listen 80;
    
    port_in_redirect off; 
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    # 1. API kérések továbbítása a backend konténernek
    location /kozitabor/api/ {
        # A 'backend' a docker-compose service neve!
        proxy_pass http://kozitabor-api:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }


    # 2. Minden más kérés a React apphoz (Frontend)
    location /kozitabor {
        try_files $uri $uri/ /kozitabor/index.html;
    }

    # Opcionális: statikus fájlok gyorsítótárazása
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}